<?php

namespace AppBundle\Repository;

/**
 * event_has_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class event_has_userRepository extends \Doctrine\ORM\EntityRepository
{
}
